### ISSUE TITLE
python3.7 + tensorflow1.14.0 + keras2.3.1 

### ISSUE THREAD

**Issue by liangxt2012** [TUT-ARG/DCASE2017-baseline-system#36]
anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 1470, in count_params   return np.prod(x.shape.as_list())
AttributeError: 'TensorVariable' object has no attribute 'as_list'

please，is it my software version is wrong???

**Comment by toni-heittola** [comment]
You can see correct software versions from requirements.txt file. This system has been develop to work with keras 2.0.8 and Theano backend.

**Comment by liangxt2012** [comment]
thank you very much for your answer，
the installation gives the following suggestion:
![image](https://user-images.githubusercontent.com/25927180/77533335-a6919380-6ed1-11ea-88ec-23dfc0b5c106.png)

**Comment by toni-heittola** [comment]
It is true that the system can be used with tensorflow backend, however, you have to install correct  tensorflow version which works with keras 2.0.8. Error you are getting is most likely related version mismatches. Unfortunately, I do not know which version of tensorflow work with this system.

Depending on which DCASE task you are interested, there are later DCASE baseline system for acoustic scene classification which have been implemented on tensorflow (e.g. https://github.com/toni-heittola/dcase2019_task1_baseline or https://github.com/toni-heittola/dcase2020_task1_baseline).

**Comment by liangxt2012** [comment]
thank you very much for your advice，I will have a try

**Comment by liangxt2012** [comment]
followed by your advice , I have successfully run throuth the model , thank you again
